import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (name) => fs.readFileSync(path.join(root, name), 'utf8');

function languageApi(language = 'en') {
  const values = new Map([['filmscript_language', language]]);
  const document = {
    readyState: 'loading',
    documentElement: { setAttribute() {} },
    addEventListener() {},
    querySelectorAll() { return []; },
  };
  const window = {
    location: { search: '', pathname: '/Editor%20v5.dc.html' },
    addEventListener() {},
    dispatchEvent() {},
  };
  const context = vm.createContext({
    window,
    document,
    localStorage: { getItem: (key) => values.get(key) || null, setItem: (key, value) => values.set(key, value) },
    URLSearchParams,
    Node: { ELEMENT_NODE: 1, TEXT_NODE: 3, DOCUMENT_NODE: 9, DOCUMENT_FRAGMENT_NODE: 11 },
    NodeFilter: { SHOW_ELEMENT: 1, SHOW_TEXT: 4 },
    CustomEvent: class { constructor(type, options) { this.type = type; this.detail = options?.detail; } },
    setTimeout() {},
    clearTimeout() {},
  });
  vm.runInContext(read('language-preference.js'), context);
  return window.filmscriptLanguage;
}

test('English and Spanish are available from one persistent FilmScript setting', () => {
  const language = read('language-preference.js');
  assert.match(language, /filmscript_language/);
  assert.match(language, /languages: Object\.freeze\(\['en', 'es'\]\)/);
  assert.match(language, /data-filmscript-language-settings/);
  assert.match(language, /fs-language-profile-item/);
  assert.match(language, /Language belongs to the profile menu/);
  assert.match(language, /data-language-option="en"/);
  assert.match(language, /data-language-option="es"/);
  assert.match(language, /filmscript:language-change/);
});

test('first workspace entry asks for an account language after profile onboarding', () => {
  const language = read('language-preference.js');
  const profile = read('profile-onboarding.js');
  assert.match(language, /INITIAL_CHOICE_ID = 'filmscript-language-initial-choice'/);
  assert.match(language, /const hasStoredLanguage = \(\) =>/);
  assert.match(language, /const shouldOfferInitialChoice = \(\) =>/);
  assert.match(language, /return \/\^\(App\|Editor v5\|Subscription\)\\\.dc/);
  assert.match(language, /Choose your language<br><span>Elige tu idioma<\/span>/);
  assert.match(language, /data-initial-language-option="en"/);
  assert.match(language, /data-initial-language-option="es"/);
  assert.doesNotMatch(language, /window\.setTimeout\(openInitialChoice, 80\)/);
  assert.match(language, /filmscript:profile-onboarding-resolved/);
  assert.match(language, /hydrateAccount/);
  assert.match(language, /filmscript_language_user_/);
  assert.match(profile, /await window\.filmscriptLanguage\?\.hydrateAccount\?\.\(account\)/);
  assert.match(language, /needsInitialChoice: shouldOfferInitialChoice/);
  assert.match(language, /closeInitialChoice\(\);/);
  for (const page of ['App.dc.html', 'Editor v5.dc.html', 'Subscription.dc.html']) {
    assert.match(read(page), /language-preference\.js\?v=[^"']+/, page);
  }
});

test('language selection warns that existing Lumiere work keeps its original language', () => {
  const language = read('language-preference.js');
  assert.match(language, /IMPORTANT · IMPORTANTE/);
  assert.match(language, /Changing FilmScript’s language later will not translate work already generated by Lumiere/);
  assert.match(language, /Cambiar después el idioma de FilmScript no traducirá el trabajo que Lumiere ya haya generado/);
  assert.match(language, /fs-language-warning/);
  assert.match(language, /role="note"/);
  assert.match(language, /color-mix\(in srgb,#c9483d/);
  assert.match(language, /prefers-reduced-transparency/);
  assert.match(language, /-webkit-backdrop-filter:blur\(42px\)/);
  assert.match(language, /lockLanguageModal/);
  assert.match(language, /trapLanguageModalFocus/);
  assert.match(language, /modalInerted\.forEach/);
});

test('language dialogs lock once and keep dynamically mounted page chrome inert', () => {
  const language = read('language-preference.js');
  const platform = read('platform-client.js');
  assert.match(language, /let lockedLanguageModal = null/);
  assert.match(language, /if \(lockedLanguageModal\) return false/);
  assert.match(language, /if \(!modal\.hidden\) \{[\s\S]*?return true;[\s\S]*?\}/);
  assert.match(language, /modalInertObserver = new MutationObserver\(\(records\) => \{/);
  assert.match(language, /record\.addedNodes\.forEach\(\(element\) => inertLanguageModalSibling\(element, modal\)\)/);
  assert.match(language, /modalInertObserver\.observe\(document\.body, \{ childList: true \}\)/);
  assert.match(language, /modalInertObserver\?\.disconnect\(\)/);
  assert.match(language, /if \(lockedLanguageModal !== modal\) return false/);
  assert.match(language, /modal\.className = 'fs-language-modal fs-language-initial-choice';[\s\S]*?modal\.hidden = true/);
  assert.match(platform, /document\.querySelectorAll\('\.fs-mobile-nav'\)\.forEach\(\(nav\) => nav\.remove\(\)\); mountMobileNav\(\)/);
});

test('language selector shows one clean label per option', () => {
  const language = read('language-preference.js');
  const options = (language.match(/<button type="button" class="fs-language-option"[\s\S]*?<\/button>/g) || [])
    .filter((option) => option.includes('data-language-option'));
  assert.equal(options.length, 2);
  assert.match(options[0], /data-language-option="en"[\s\S]*?<strong>English<\/strong><\/span>/);
  assert.match(options[1], /data-language-option="es"[\s\S]*?<strong>Español<\/strong><\/span>/);
  assert.equal(options.some((option) => option.includes('<small>')), false);
});

test('Spanish profile theme labels use night and day language', () => {
  const language = read('language-preference.js');
  assert.match(language, /'Dark theme': 'Modo noche'/);
  assert.match(language, /'Light theme': 'Modo día'/);
  assert.match(language, /'Switch to dark mode': 'Cambiar a modo noche'/);
  assert.match(language, /'Switch to light mode': 'Cambiar a modo día'/);
});

test('Spanish Scripts chrome localizes accessible labels and slow-load recovery copy', () => {
  const spanish = languageApi('es').t;
  assert.equal(spanish('FilmScript, go to scripts'), 'FilmScript, ir a guiones');
  assert.equal(spanish('Account menu'), 'Menú de cuenta');
  assert.equal(
    spanish('Your scripts are taking longer than expected. Please try again.'),
    'Tus guiones están tardando más de lo esperado. Inténtalo de nuevo.'
  );
});

test('Spanish afternoon greetings use natural, playful copy', () => {
  const app = read('App.dc.html');
  const language = read('language-preference.js');
  for (const copy of [
    'El café ya hizo su parte. Ahora toca rescatar ese segundo acto antes de que pida vacaciones.',
    'La tarde está dorada y ese tercer acto sigue pidiendo auxilio. Vamos a darle una vuelta.',
  ]) {
    assert.match(app, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
    assert.match(language, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
  assert.doesNotMatch(app, /Una hora perfecta para los segundos actos/);
  assert.doesNotMatch(app, /La luz se vuelve dorada\. Un buen momento/);
});

test('every user-facing FilmScript page loads the shared language preference', () => {
  for (const page of ['App.dc.html', 'Editor v5.dc.html', 'Features.dc.html', 'Pricing.dc.html', 'Subscription.dc.html', 'SharedProject.html', 'auth-complete.html', 'auth-google.html']) {
    assert.match(read(page), /language-preference\.js/, page);
  }
  assert.match(read('scripts/build-netlify.mjs'), /"language-preference\.js"/);
});

test('Shared Project and Google authentication routes have complete Spanish UI coverage', () => {
  const shared = read('SharedProject.html');
  const authComplete = read('auth-complete.html');
  const authGoogle = read('auth-google.html');
  const spanish = languageApi('es').t;
  const english = languageApi('en').t;

  for (const page of [shared, authComplete, authGoogle]) {
    assert.match(page, /language-preference\.js\?v=20260820-i18n3/);
  }

  for (const [source, translated] of [
    ['Project View · FilmScript', 'Vista del proyecto · FilmScript'],
    ['Opening Project View', 'Abriendo la vista del proyecto'],
    ['Request access', 'Solicitar acceso'],
    ['Password protected', 'Protegido con contraseña'],
    ['Open in FilmScript', 'Abrir en FilmScript'],
    ['No shared sections', 'No hay secciones compartidas'],
    ['Refresh latest content', 'Actualizar el contenido más reciente'],
    ['We could not send your access request. Please try again.', 'No pudimos enviar tu solicitud de acceso. Inténtalo de nuevo.'],
    ['We could not prepare this export. Please try again.', 'No pudimos preparar esta exportación. Inténtalo de nuevo.'],
    ['Finishing sign in · FilmScript', 'Finalizando el inicio de sesión · FilmScript'],
    ['Opening your scripts…', 'Abriendo tus guiones…'],
    ['We could not finish your sign in. Please try again.', 'No pudimos completar tu inicio de sesión. Inténtalo de nuevo.'],
    ['FilmScript · Sign in', 'FilmScript · Iniciar sesión'],
    ['Connecting to Google…', 'Conectando con Google…'],
  ]) {
    assert.equal(spanish(source), translated, source);
    assert.equal(english(source), source, source);
  }

  const sharedUiLiterals = [...shared.matchAll(/ui(?:Esc)?\('([^']+)'\)/g)].map((match) => match[1]);
  assert.ok(sharedUiLiterals.length >= 45);
  for (const source of new Set(sharedUiLiterals)) {
    assert.notEqual(spanish(source), source, `Shared Project UI is missing Spanish copy: ${source}`);
  }

  assert.match(shared, /const ui = \(value\) => window\.filmscriptLanguage/);
  assert.match(shared, /const publicError = \(error, fallback/);
  assert.match(shared, /root\.querySelector\('strong'\)\.textContent = ui\('Opening Project View'\)/);
  assert.match(shared, /aria-label="\$\{uiEsc\('Refresh latest content'\)\}"/);
  assert.match(shared, /aria-label="\$\{uiEsc\('Email address'\)\}"/);
  assert.match(shared, /data-project-content/);
  assert.doesNotMatch(shared, /error\.textContent = failure\.message/);
  assert.doesNotMatch(shared, /alert\(error\.message\)/);
  assert.match(authComplete, /role="status" aria-live="polite"/);
  assert.match(authComplete, /message\.textContent = ui\('We could not finish your sign in/);
  assert.match(authComplete, /document\.querySelector\('h1'\)\.textContent = ui\('Opening your scripts…'\)/);
  assert.match(authGoogle, /role="status" aria-live="polite"/);
  assert.match(authGoogle, /querySelector\('\[role="status"\]'\)\.textContent = window\.filmscriptLanguage/);
});

test('People & Access, invitations, and guest access preserve a complete Spanish interface', () => {
  const language = read('language-preference.js');
  const client = read('platform-client.js');
  const invitation = read('Invitation.html');
  const invitationAccess = read('invitation-access.js');
  const guest = read('GuestAccess.html');
  const guestAccess = read('guest-access.js');

  for (const [english, spanish] of [
    ['People & Access', 'Personas y acceso'],
    ['Invite a collaborator', 'Invitar a un colaborador'],
    ['Project collaboration settings', 'Configuración de colaboración del proyecto'],
    ['Cinematic role', 'Rol cinematográfico'],
    ['Module permissions', 'Permisos por módulo'],
    ['Financial access', 'Acceso financiero'],
    ['No financial access', 'Sin acceso financiero'],
    ['Temporary Guest', 'Invitado temporal'],
    ['Pending Invitations', 'Invitaciones pendientes'],
    ['Guest project access', 'Acceso de invitado al proyecto'],
    ['Opening your secure invitation', 'Abriendo tu invitación segura'],
    ['You are invited to collaborate', 'Te invitaron a colaborar'],
  ]) {
    assert.match(language, new RegExp(`'${english.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}': '${spanish.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}'`), english);
  }

  assert.match(language, /value\.match\(\/\^Access for \(\.\+\)\$\//);
  assert.match(language, /value\.match\(\/\^Read only access expires \(\.\+\)\\\.\$\//);
  assert.match(language, /value\.match\(\/\^\(\\d\+\) areas · \(\.\+\)\$\//);
  assert.match(client, /dialog\('People & Access'/);
  assert.match(client, /Invite a collaborator/);

  for (const page of [invitation, guest]) {
    assert.match(page, /language-preference\.js\?v=20260820-i18n3/);
  }
  assert.match(invitationAccess, /document\.title = `\$\{localize\('Project invitation'\)\} \| FilmScript`/);
  assert.match(guestAccess, /document\.title = `\$\{localize\('Guest access'\)\} \| FilmScript`/);
  assert.match(guestAccess, /toLocaleString\(interfaceLocale\(\)\)/);
  assert.match(client, /localizedDate\(invitation\.expiresAt\)/);
  assert.match(client, /confirm\(uiText\('Remove this person from the project now\?'\)\)/);
});

test('People & Access dynamic roles, permissions, dates, and names follow the active interface language', () => {
  const spanish = languageApi('es').t;
  const english = languageApi('en').t;

  assert.equal(spanish('People & Access'), 'Personas y acceso');
  assert.equal(spanish('3 areas · Script View, Breakdown Edit'), '3 áreas · Guion Ver, Desglose Editar');
  assert.equal(spanish('script: edit'), 'Guion: Editar');
  assert.equal(spanish('Access for Sofia'), 'Acceso para Sofia');
  assert.equal(spanish('Read only access expires Aug 20, 2026.'), 'El acceso de solo lectura vence Aug 20, 2026.');
  assert.equal(english('People & Access'), 'People & Access');
});

test('terms disclose durable Free grants and Creator and Full image-credit rules', () => {
  for (const page of ['App.dc.html', 'Features.dc.html', 'Pricing.dc.html']) {
    const source = read(page);
    assert.match(source, /one AI script analysis, one AI breakdown, and one AI storyboard or shot list per account/, page);
    assert.match(source, /not restored by deleting a script/, page);
    assert.match(source, /Creator includes .*AI text tools.*100 image credits/, page);
    assert.match(source, /Full includes 1,000 image credits/, page);
    assert.match(source, /uses 3 credits/, page);
  }
  const language = read('language-preference.js');
  assert.match(language, /Free incluye un pequeño número de prompts de Lumiere/);
  assert.match(language, /Full incluye 1,000 créditos de imagen/);
});

test('the Lumiere brand name is never accented in the interface', () => {
  for (const file of ['language-preference.js', 'lumiere-preferences.js', 'analysis-workspace.js', 'server.js', 'Editor v5.dc.html']) {
    assert.equal(read(file).includes('Lumière'), false, `${file} still contains accented Lumiere copy`);
  }
});

test('Analysis has Spanish copy for its empty state, focus cards, drawers, and dynamic labels', () => {
  const language = read('language-preference.js');
  const analysis = read('analysis-workspace.js');
  for (const [english, spanish] of [
    ['Your screenplay is ready to read', 'Tu guion está listo para leerse'],
    ['Analyze', 'Analizar'],
    ['Reanalyze', 'Volver a analizar'],
    ['Your script has changed since this analysis was generated.', 'Tu guion ha cambiado desde que se generó este análisis.'],
    ['Lumiere focus', 'Enfoque de Lumiere'],
    ['Analysis summary', 'Resumen del análisis'],
    ['strengths', 'fortalezas'],
    ['priorities', 'prioridades'],
    ['scenes read', 'escenas leídas'],
    ['Explore further', 'Explorar más'],
    ['Production lens', 'Perspectiva de producción'],
    ['Refresh', 'Actualizar'],
    ['Try again', 'Intentar de nuevo'],
    ['No scenes are associated with this selection.', 'No hay escenas asociadas con esta selección.'],
  ]) {
    assert.match(analysis, new RegExp(english.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')), english);
    assert.match(language, new RegExp(`'${english.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}': '${spanish.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}'`), spanish);
  }
  assert.match(language, /More screenplay context is needed before Lumiere can interpret/);
  assert.match(language, /FilmScript Creator at \$24\.99 \/ month unlocks ongoing Lumiere work/);
  assert.match(language, /value\.match\(\/\^\(\\d\+\) scenes · current draft\$/);
  assert.match(language, /value\.match\(\/\^Updated \(\.\+\)\$/);
  assert.match(analysis, /window\.filmscriptLanguage\?\.get\?\.\(\) === 'es'/);
  assert.match(analysis, /filmscript:language-change/);
  assert.match(analysis, /filmscriptLanguage\?\.t\?\.\(sourceQuestion, 'es'\)/);
  assert.match(analysis, /const strengthsLabel = strengths\.length === 1/);
  assert.match(analysis, /const fallbackStages = spanish \? \['Inicio', 'Conflicto', 'Pico', 'Desenlace'\]/);
  assert.match(analysis, /const sceneLabel = spanish \? 'Escena' : 'Scene'/);
  for (const status of [
    'Reading screenplay',
    'Identifying scenes',
    'Mapping characters',
    'Reviewing locations',
    'Evaluating production requirements',
    'Building analysis',
    'Finalizing results',
  ]) assert.match(language, new RegExp(`'${status.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}'`));
});

test('Budget translates every primary view, cash-flow title, expense state, and default account label', () => {
  const language = read('language-preference.js');
  const budget = read('budget-workspace.js');
  const budgetModel = read('budget-model.js');
  for (const [english, spanish] of [
    ['Budget Quick View', 'Vista rápida del presupuesto'],
    ['Budget Summary', 'Resumen del presupuesto'],
    ['Budget Breakdown', 'Desglose del presupuesto'],
    ['Cash Flow', 'Flujo de caja'],
    ['Weekly profile', 'Perfil semanal'],
    ['Finance Plan', 'Plan financiero'],
    ['Expense Report', 'Informe de gastos'],
    ['Budget Settings', 'Ajustes del presupuesto'],
    ['Loading Budget', 'Cargando presupuesto'],
    ['Budget could not be opened', 'No se pudo abrir el presupuesto'],
    ['No expenses yet', 'Aún no hay gastos'],
    ['Choose a budget line', 'Elegir una partida presupuestaria'],
    ['Record as unexpected cost', 'Registrar como costo inesperado'],
    ['Project Development', 'Desarrollo del proyecto'],
    ['Camera Equipment', 'Equipo de cámara'],
    ['Picture Postproduction', 'Postproducción de imagen'],
  ]) {
    assert.match(`${budget}\n${budgetModel}`, new RegExp(english.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')), english);
    assert.match(language, new RegExp(`'${english.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}': '${spanish.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}'`), spanish);
  }
  assert.match(language, /value\.match\(\/\^Prep Week/);
  assert.match(language, /value\.match\(\/\^\(\\d\+\) payments\? need a date/);
  assert.match(language, /value\.match\(\/\^Preview of/);
  assert.match(budget, /filmscript:language-change/);
  assert.match(budget, /displayLabel\(value\)/);
});

test('authored screenplay titles and saved conversations are excluded from UI translation', () => {
  assert.match(read('App.dc.html'), /fs-script-card-title" data-i18n-skip/);
  assert.match(read('App.dc.html'), /data-i18n-skip style="\{\{ m\.bubbleStyle \}\}"/);
  assert.match(read('Editor v5.dc.html'), /data-i18n-skip class="v5-chat-bubble"/);
  assert.match(read('Editor v5.dc.html'), /\{\{ part\.text \}\}/);
  assert.match(read('language-preference.js'), /\[data-fs-page\], \[data-v5-cover\]/);
});

test('durable Lumiere analysis stays in its generated language while interface labels remain translatable', () => {
  const language = read('language-preference.js');
  const analysis = read('analysis-workspace.js');
  assert.match(language, /\[data-lumiere-generated\], \[data-project-content\]/);
  assert.match(analysis, /<summary>Evidence<\/summary><blockquote data-lumiere-generated>/);
  assert.match(analysis, /<h3 data-lumiere-generated>/);
  assert.match(analysis, /data-lumiere-generated>\$\{escapeHtml\(takeaway\.title\)\}/);
  assert.match(analysis, /data-project-content>\$\{escapeHtml\(scene\.heading\)\}/);
  assert.doesNotMatch(analysis, /<summary data-lumiere-generated>Evidence/);
});

test('durable Breakdown, Shot List, Title Room, and chat values keep their source language', () => {
  const breakdown = read('breakdown-workspace.js');
  const editor = read('Editor v5.dc.html');
  const client = read('platform-client.js');

  assert.match(breakdown, /<strong data-project-content>\$\{escapeHtml\(element\.name\)\}<\/strong>/);
  assert.match(breakdown, /<p data-project-content>\$\{escapeHtml\(element\.description\)\}<\/p>/);
  assert.match(breakdown, /<strong\$\{info\.headingIsProjectContent \? ' data-project-content' : ''\}>\$\{escapeHtml\(info\.heading\)\}<\/strong>/);
  assert.doesNotMatch(breakdown, /<h4 data-project-content>/);

  assert.match(editor, /breakdownSceneHeadingProjectContent[\s\S]*?<span data-project-content>\{\{ breakdownSceneHeading \}\}<\/span>/);
  assert.match(editor, /v5-breakdown-entry-name" data-project-content>\{\{ entry\.name \}\}/);
  assert.match(editor, /v5-shotlist-scene-title" data-project-content>\{\{ scene\.title \}\}/);
  assert.match(editor, /data-project-content style="font-size: 11\.5px; line-height: 1\.45;[^>]+>\{\{ shot\.descriptionDisplay \}\}/);
  assert.match(editor, /data-lumiere-generated style="font-size: 15px;[^>]+>\{\{ title\.title \}\}/);
  assert.match(editor, /v5-title-analysis" data-lumiere-generated[^>]+>\{\{ titleRoomComparison \}\}/);
  assert.match(editor, /breakdownDescriptionInterfaceContent[^>]+>[\s\S]*?<span class="v5-breakdown-value">\{\{ breakdownDescription \}\}<\/span>/);
  assert.match(editor, /shot\.descriptionMissing[^>]+>[\s\S]*?<span style="font-size: 11\.5px; line-height: 1\.45;[^>]+>\{\{ shot\.descriptionDisplay \}\}<\/span>/);
  assert.doesNotMatch(editor, /v5-breakdown-cell-label" data-project-content/);
  assert.doesNotMatch(editor, /v5-title-action"[^>]*data-lumiere-generated/);

  assert.equal((client.match(/<p data-project-content(?: data-i18n-skip)?>\$\{escapeHtml\(item\.body\)\}<\/p>/g) || []).length, 2);
  assert.doesNotMatch(client, /<time data-project-content>/);
});

test('editor workflows and destructive confirmations use the shared language layer', () => {
  const language = read('language-preference.js');
  assert.match(language, /'Title Page Designer': 'Diseñador de portada'/);
  assert.match(language, /'Adjust all pending': 'Ajustar todas las pendientes'/);
  assert.match(language, /Page \(\\d\+\) of \(\\d\+\)/);
  assert.match(read('App.dc.html'), /filmscriptLanguage\?\.t\(confirmation\)/);
});

test('Breakdown, Stripboard, Shot List, operational feedback, and Editor ARIA follow ES and EN', () => {
  const spanish = languageApi('es').t;
  const english = languageApi('en').t;
  const pairs = [
    ['Loading Breakdown', 'Cargando desglose'],
    ['Build the breakdown your way.', 'Crea el desglose a tu manera.'],
    ['Previous breakdown scene', 'Escena anterior del desglose'],
    ['More breakdown export options', 'Más opciones de exportación del desglose'],
    ['Production schedule version history', 'Historial de versiones del plan de producción'],
    ['Assign shoot location to selected scenes', 'Asignar locación de rodaje a las escenas seleccionadas'],
    ['Shot duration clock', 'Selector de duración del plano'],
    ['Reference preview', 'Vista previa de referencia'],
    ['Could not load Shot List data.', 'No se pudieron cargar los datos de la lista de planos.'],
    ['This scene is already over its Stripboard time. Reduce coverage before adding time.', 'Esta escena ya excede su tiempo en el plan de rodaje. Reduce la cobertura antes de agregar tiempo.'],
    ['Scene headings start with INT. or EXT.', 'Los encabezados de escena comienzan con INT. o EXT.'],
    ['Your full Lumiere breakdown is ready.', 'Tu desglose completo de Lumiere está listo.'],
  ];
  for (const [source, translation] of pairs) {
    assert.equal(spanish(source), translation, source);
    assert.equal(english(source), source, source);
  }

  assert.equal(spanish('Open scene 12 in script'), 'Abrir la escena 12 en el guion');
  assert.equal(spanish('Assign shoot location for scene 4'), 'Asignar locación de rodaje a la escena 4');
  assert.equal(spanish('Manual breakdown ready for 2 scenes.'), 'Desglose manual listo para 2 escenas.');
  assert.equal(spanish('INT DAY'), 'INT DAY');
  assert.equal(spanish('EXT NIGHT'), 'EXT NIGHT');
});

test('Editor rerenders locale-aware controls and protects only durable production values', () => {
  const editor = read('Editor v5.dc.html');
  assert.match(editor, /window\.addEventListener\('filmscript:language-change', this\._languageHandler\)/);
  assert.match(editor, /new Intl\.DateTimeFormat\(interfaceLocale/);
  assert.match(editor, /v5-strip-ie-day"><span data-project-content>\{\{ row\.intExt \}\}<\/span><span data-project-content>\{\{ row\.dayNight \}\}<\/span>/);
  assert.match(editor, /row\.setNameProjectContent[\s\S]*?<span data-project-content>\{\{ row\.setName \}\}<\/span>/);
  assert.match(editor, /shotReferencePreviewSizeProjectContent[\s\S]*?<span data-project-content>\{\{ shotReferencePreviewSize \}\}<\/span>/);
  assert.match(editor, /shotReferencePreviewAngleProjectContent[\s\S]*?<span data-project-content>\{\{ shotReferencePreviewAngle \}\}<\/span>/);
  assert.match(editor, /shotReferencePreviewMovementProjectContent[\s\S]*?<span data-project-content>\{\{ shotReferencePreviewMovement \}\}<\/span>/);
  assert.doesNotMatch(editor, />Size<\/div><div[^>]*data-project-content/);
  assert.doesNotMatch(editor, />Angle<\/div><div[^>]*data-project-content/);
  assert.doesNotMatch(editor, />Movement<\/div><div[^>]*data-project-content/);
});
